[package]
name = "jarvis"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
dotenv = "0.15"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
